# 1. Create a 3x3x3 array with random values?

In [3]:
import numpy as np

In [2]:
random_arr = np.random.randint(1,100, size=(3,3,3))
random_arr

array([[[97,  1,  9],
        [31, 41, 94],
        [35, 28, 22]],

       [[99, 54, 73],
        [64, 82, 59],
        [29, 79, 58]],

       [[ 9, 85, 49],
        [16, 12, 42],
        [80, 33, 27]]])

# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal?

In [7]:
np.diag([1,2,3,4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3. Create a 8x8 matrix and fill it with a checkboard pattern?

In [8]:
import numpy as np

print ("Checkboard Pattern is: ")
x = np.zeros((8,8), dtype=int)

x[1::2,::2] = 1
x[::2,1::2] = 1

print (x)

Checkboard Pattern is: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix?

In [9]:
import numpy as np

x = np.random.random((5,5))

print ("Original Array is: ")
print (x)

xmax, xmin = x.max(), x.min()

x = (x - xmin)/ (xmax - xmin)

print ("After Normalization: ")
print (x)

Original Array is: 
[[0.43946124 0.88615055 0.65985327 0.71912365 0.68591923]
 [0.60458543 0.65137469 0.47772263 0.33359969 0.36193906]
 [0.08745861 0.94747118 0.03335603 0.02033746 0.57742132]
 [0.92368859 0.81012211 0.24213693 0.15514565 0.3457517 ]
 [0.95112957 0.47408852 0.25607624 0.80513303 0.89992298]]
After Normalization: 
[[0.4502872  0.93018954 0.68706621 0.75074357 0.71507028]
 [0.627689   0.67795722 0.49139348 0.33655445 0.36700096]
 [0.07211185 0.9960696  0.01398655 0.         0.59850514]
 [0.97051868 0.84850811 0.23829109 0.14483168 0.34961001]
 [1.         0.48748915 0.25326684 0.84314807 0.94498601]]


# 5. How to find common values between two arrays?

In [12]:
import numpy as np

arr1 = np.array([1,2,3])
print ("Array 1 is: ", arr1)

arr2 = np.array([5,4,1])
print ("Array 2 is: ", arr2)

print ("Common values in the array 1 and array 2 is: ")

print(np.intersect1d(arr1, arr2))
np.set_printoptions(threshold=np.inf)


Array 1 is:  [1 2 3]
Array 2 is:  [5 4 1]
Common values in the array 1 and array 2 is: 
[1]


# 6. How to get the dates of yesterday, today and tomorrow?

In [13]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's Date: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today's Date: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's Date: ",tomorrow)

Yestraday's Date:  2020-07-26
Today's Date:  2020-07-27
Tomorrow's Date:  2020-07-28


# 7. Consider two random array A and B, check if they are equal?

In [17]:
A = np.array([[8.10],[5,1]])
B = np.array([[8,10],[2,5]])
comparison = A == B
equal_arrays = comparison.all()
print (equal_arrays)

False


# 8. Create random vector of size 10 and replace the maximum value by 0

In [19]:
from numpy import array
print("Random vector of size 10 is:")
v = np.random.randint(1,20, size = 10)
print(v)
v[v.argmax()] = 0
print("Replacing the maximum value by 0:")
print(v)

Random vector of size 10 is:
[14 11 18 14  4  6  6 17 16  8]
Replacing the maximum value by 0:
[14 11  0 14  4  6  6 17 16  8]


# 9. How to print all the values of an array?

In [21]:
a = np.arange(50)
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


# 10. Subtract the mean of each row of a matrix?

In [23]:
import numpy as np
print("Original matrix:")
x = np.arange(12).reshape(3,4)
print(x)
print("Subtracting the mean of each row of the matrix:")
y = x - x.mean(axis=1, keepdims = True)
print(y)

Original matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Subtracting the mean of each row of the matrix:
[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?


In [24]:
x = np.random.randint(1,8,8)
print("Given vector:", x)
y = np.random.randint(x)
z = []
y.sort()
for i in y:
    if i not in z:
        z.append(i)

for j in z:
    a[j] += 1

print("Indexing vector:", y)
print("Result:",x)

Given vector: [6 5 1 1 2 7 2 4]
Indexing vector: [0 0 0 0 0 0 1 3]
Result: [6 5 1 1 2 7 2 4]


# 12.How to get the diagonal of a dot product?

In [26]:
a = [[8,2],[9,7]]
b = [[5,1],[6,8]]
c = np.diag(np.dot(a,b))
c

array([52, 65])

# 13.How to find the most frequent value in an array?


In [27]:
import numpy as np
x = np.random.randint(0, 10, 20)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[2 4 8 0 0 1 1 1 2 3 9 8 5 2 1 6 9 6 0 4]
Most frequent value in the above array:
1


# 14. How to get the n largest values of an array?

In [29]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print("Largest value of the array is",x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
Largest value of the array is [9]


# 15. How to create a record array from a regular array?

In [32]:
import numpy as np
a1=np.array(['Toyota','Honda','Audi','BMW'])
a2=np.array(['White','Pink','Purple','Green'])
result= np.core.records.fromarrays([a1, a2])
print(result[0])
print(result[1])
print(result[2])
print(result[3])

('Toyota', 'White')
('Honda', 'Pink')
('Audi', 'Purple')
('BMW', 'Green')
